export const emojiGroups = {
  faces: [
    { code: '😀', name: '笑脸' },
    { code: '😄', name: '开心' },
    { code: '😊', name: '害羞' },
    { code: '😂', name: '笑哭' },
    { code: '😍', name: '爱心眼' },
    { code: '🤔', name: '思考' },
    { code: '😴', name: '睡觉' },
    { code: '😭', name: '大哭' },
    { code: '😡', name: '生气' },
    { code: '🤮', name: '呕吐' },
    { code: '🥰', name: '喜欢' },
    { code: '😘', name: '飞吻' },
    { code: '🙄', name: '白眼' },
    { code: '😅', name: '尴尬' },
    { code: '😱', name: '害怕' },
    { code: '🤣', name: '笑倒' },
    { code: '🥺', name: '可怜' },
    { code: '😇', name: '天使' },
    { code: '🤩', name: '星星眼' },
    { code: '🤪', name: '疯狂' },
    { code: '😋', name: '美味' },
    { code: '🤫', name: '嘘' },
    { code: '🤭', name: '偷笑' },
    { code: '🥱', name: '哈欠' }
  ],
  gestures: [
    { code: '👍', name: '赞' },
    { code: '👎', name: '踩' },
    { code: '👌', name: 'OK' },
    { code: '✌️', name: '胜利' },
    { code: '🤝', name: '握手' },
    { code: '👋', name: '挥手' },
    { code: '🙏', name: '祈祷' },
    { code: '💪', name: '加油' },
    { code: '👏', name: '鼓掌' },
    { code: '🤘', name: 'Rock' },
    { code: '✊', name: '加油' },
    { code: '👊', name: '拳头' },
    { code: '🤞', name: '许愿' },
    { code: '🤙', name: '打电话' },
    { code: '👈', name: '左指' },
    { code: '👉', name: '右指' },
    { code: '👆', name: '上指' },
    { code: '👇', name: '下指' }
  ],
  hearts: [
    { code: '❤️', name: '红心' },
    { code: '💔', name: '心碎' },
    { code: '💖', name: '闪亮心' },
    { code: '💘', name: '丘比特之心' },
    { code: '💝', name: '礼物心' },
    { code: '💓', name: '跳动心' },
    { code: '💕', name: '双心' },
    { code: '💞', name: '旋转心' },
    { code: '🧡', name: '橙心' },
    { code: '💛', name: '黄心' },
    { code: '💚', name: '绿心' },
    { code: '💙', name: '蓝心' },
    { code: '💜', name: '紫心' },
    { code: '🤎', name: '棕心' },
    { code: '🖤', name: '黑心' },
    { code: '🤍', name: '白心' }
  ],
  animals: [
    { code: '🐱', name: '猫咪' },
    { code: '🐶', name: '狗狗' },
    { code: '🐼', name: '熊猫' },
    { code: '🐨', name: '考拉' },
    { code: '🦊', name: '狐狸' },
    { code: '🦁', name: '狮子' },
    { code: '🐯', name: '老虎' },
    { code: '🐷', name: '小猪' },
    { code: '🐮', name: '奶牛' },
    { code: '🐸', name: '青蛙' },
    { code: '🐰', name: '兔子' },
    { code: '🦄', name: '独角兽' },
    { code: '🐙', name: '章鱼' },
    { code: '🦋', name: '蝴蝶' },
    { code: '🐞', name: '瓢虫' },
    { code: '🦜', name: '鹦鹉' }
  ],
  food: [
    { code: '🍎', name: '苹果' },
    { code: '🍕', name: '披萨' },
    { code: '🍖', name: '肉' },
    { code: '🍜', name: '面条' },
    { code: '🍦', name: '冰淇淋' },
    { code: '🍺', name: '啤酒' },
    { code: '☕', name: '咖啡' },
    { code: '🍩', name: '甜甜圈' },
    { code: '🍔', name: '汉堡' },
    { code: '🌭', name: '热狗' },
    { code: '🍟', name: '薯条' },
    { code: '🥤', name: '饮料' },
    { code: '🍱', name: '便当' },
    { code: '🍣', name: '寿司' },
    { code: '🥗', name: '沙拉' },
    { code: '🍪', name: '饼干' }
  ],
  weather: [
    { code: '☀️', name: '太阳' },
    { code: '⛅', name: '多云' },
    { code: '☔', name: '下雨' },
    { code: '❄️', name: '雪花' },
    { code: '⚡', name: '闪电' },
    { code: '🌈', name: '彩虹' },
    { code: '🌙', name: '月亮' },
    { code: '⭐', name: '星星' },
    { code: '🌊', name: '海浪' },
    { code: '🌪️', name: '龙卷风' },
    { code: '☂️', name: '雨伞' },
    { code: '⛄', name: '雪人' }
  ],
  activities: [
    { code: '⚽', name: '足球' },
    { code: '🏀', name: '篮球' },
    { code: '🎮', name: '游戏' },
    { code: '🎵', name: '音乐' },
    { code: '🎨', name: '艺术' },
    { code: '📚', name: '读书' },
    { code: '🎬', name: '电影' },
    { code: '🎪', name: '马戏团' },
    { code: '⚾', name: '棒球' },
    { code: '🎾', name: '网球' },
    { code: '🏓', name: '乒乓球' },
    { code: '🎭', name: '表演' },
    { code: '🎤', name: '唱歌' },
    { code: '🎸', name: '吉他' },
    { code: '🎯', name: '射击' },
    { code: '🎲', name: '骰子' }
  ],
  objects: [
    { code: '💡', name: '灯泡' },
    { code: '🔋', name: '电池' },
    { code: '📱', name: '手机' },
    { code: '💻', name: '电脑' },
    { code: '⌚', name: '手表' },
    { code: '🎁', name: '礼物' },
    { code: '🔑', name: '钥匙' },
    { code: '🔨', name: '锤子' },
    { code: '✂️', name: '剪刀' },
    { code: '🔍', name: '放大镜' },
    { code: '🎈', name: '气球' },
    { code: '🎀', name: '丝带' }
  ],
  symbols: [
    { code: '❌', name: '错误' },
    { code: '✅', name: '正确' },
    { code: '⭕', name: '圆圈' },
    { code: '❗', name: '感叹号' },
    { code: '❓', name: '问号' },
    { code: '💯', name: '满分' },
    { code: '🔞', name: '禁止' },
    { code: '⚠️', name: '警告' },
    { code: '♻️', name: '回收' },
    { code: '🔰', name: '新手' },
    { code: '✨', name: '闪烁' },
    { code: '💫', name: '星星' },
    { code: '🌟', name: '星星' },
    { code: '🌈', name: '彩虹' }
  ]
}
